server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:    #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit:  #表示定义的名称，用于binding整合
          type: rabbit   #消息组件类型
          environment:  #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input: #这个名字是个通道的名称
          destination: studyExchange   #表示要使用的Exchange名称定义
          content-type: application/json  #设置消息类型，本次为json 文本设置为text/plain
          binder: defaultRabbit               #设置要绑定的消息服务的具体设置:
          group: atguiguA
eureka:
  client:
    service-url:
      # 设置与Eureka server 交互的地址查询服务和注册服务都需要这个地址
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: receive-8802.com
    prefer-ip-address: true    #访问路径可以正确显示路径
    #Eureka客户端向服务端发送心跳的时间间隔，单位为毫秒  默认30
    lease-renewal-interval-in-seconds: 2
    #超过了五秒的时间间隔
    lease-expiration-duration-in-seconds: 5
logging:
  group:
