server:
  port: 8003

spring:
  application:
    name: cloud-payment-service

eureka:
  client:
    register-with-eureka: true    #false 表示不向服务注册自己
    fetch-registry: true          #false 表示自己端就是注册中心，我的职责就是维护实例，平不需要检测实例
    service-url:
      # 设置与Eureka server 交互的地址查询服务和注册服务都需要这个地址
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8003
    prefer-ip-address: true    #访问路径可以正确显示路径
    #Eureka客户端向服务端发送心跳的时间间隔，单位为毫秒  默认30
    lease-renewal-interval-in-seconds: 1
    #
    lease-expiration-duration-in-seconds: 2020