


spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1                        #采样值介于0到一之间   1表示全部采集
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:DLYH
    username: AUTEK
    password: FLYVIDEO
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
eureka:
  client:
    register-with-eureka: true    #false 表示不向服务注册自己
    fetch-registry: true          #false 表示自己端就是注册中心，我的职责就是维护实例，平不需要检测实例
    service-url:
     # 设置与Eureka server 交互的地址查询服务和注册服务都需要这个地址
      defaultZone: http://localhost:7001/eureka
     #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true    #访问路径可以正确显示路径
    #Eureka客户端向服务端发送心跳的时间间隔，单位为毫秒  默认30
    lease-renewal-interval-in-seconds: 1
#
    lease-expiration-duration-in-seconds: 2020

#mybatis的配置
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.atguiggu.springcloud.entites


mybatis-plus:
    mapper-locations: classpath*:/mapper/*.xml
    type-aliases-package: com.atguiggu.springcloud.entites
    configuration:
      map-underscore-to-camel-case: true
server:
  port: 8001
