server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #路由的id，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
        #  uri: http://localhost:8001       #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**      #断言 路径相匹配的进行路由
            - After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
        #    - Cookie=username,zzyy

        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**




eureka:
  client:
    register-with-eureka: true    #false 表示不向服务注册自己
    fetch-registry: true          #false 表示自己端就是注册中心，我的职责就是维护实例，平不需要检测实例
    service-url:
      # 设置与Eureka server 交互的地址查询服务和注册服务都需要这个地址
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
