server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx__group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3366/seata_order
    username: root
    password: root

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

#mybatis的配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.atguiggu.springcloud.entites


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.atguiggu.springcloud.entites
  configuration:
    map-underscore-to-camel-case: true