server:
  port: 80


eureka:
  client:
    register-with-eureka: false
    service-url:
       defaulyZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
ribbon:
  #指得是建立连接所需要的时间，适用于网络状态正常的情况下，俩端连接所系要的时间
  ReadTimeout: 5000
  #指得是建立连接后从服务器读取到可用资源作用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控那个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug